// <auto-generated />
using System;
using DesafioAmsterdam;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioAmsterdam.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180821230906_TableData")]
    partial class TableData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioAmsterdam.TableData", b =>
                {
                    b.Property<int>("TabeleDataID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RowData");

                    b.Property<int?>("TableHeaderTableID");

                    b.HasKey("TabeleDataID");

                    b.HasIndex("TableHeaderTableID");

                    b.ToTable("TableData");
                });

            modelBuilder.Entity("DesafioAmsterdam.TableHeaders", b =>
                {
                    b.Property<int>("TableID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HeaderValues");

                    b.Property<string>("TableName");

                    b.HasKey("TableID");

                    b.ToTable("TableHeaders");
                });

            modelBuilder.Entity("DesafioAmsterdam.TableData", b =>
                {
                    b.HasOne("DesafioAmsterdam.TableHeaders", "TableHeader")
                        .WithMany()
                        .HasForeignKey("TableHeaderTableID");
                });
#pragma warning restore 612, 618
        }
    }
}
